### ISSUE TITLE
Feature request: CLI Program

### ISSUE THREAD

**Issue by afifurrohman-id** [matthewhartstonge/argon2#64]
Hello, thankyou for awesome library, could you add a CLI program too in this library? 
Which can be optionally installing with `go install https://github.com/matthewhartstonge/argon2/cmd/argon2@latest`

**Comment by afifurrohman-id** [comment]
Which will help someone who want to hash a password using command line directly

**Comment by matthewhartstonge** [comment]
Love this idea! I've created a cli to do this internally where I work, it's pretty quick to do so I'll see if I can find time over the next month to get it added here :)

**Comment by matthewhartstonge** [comment]
Does this work for you? https://github.com/matthewhartstonge/argon2/tree/feature/cli/cmd/argon2 
Main aim was to use `stdlib` to minimise dependencies being a lib.

You can test an install by running:

```
GOPROXY="direct" go install github.com/matthewhartstonge/argon2/cmd/argon2@feature/cli
```

As for a formal release, I'll need to work on setting up `go-releaser` to publish verified cross-platform binaries.

**Comment by afifurrohman-id** [comment]
> I'm thinking of changing how the program takes the password in currently. As it stands the password would be stored in bash history - which isn't great from a secops point of view 😬

i think stdin still good, place like `base64` does

**Comment by matthewhartstonge** [comment]
Have merged in!
Can be installed directly now:

`go install github.com/matthewhartstonge/argon2/cmd/argon2@latest`

Have almost got goreleaser working for binary publishing on Github releases. I noticed that MacOS eats the binaries it's pushing out (due to being made by an 'unidentified developer') so I'm currently going through the required processes to enable Apple binary signing and notarisation.
